name: jarvis-ci

on:
  pull_request:
    branches:
    - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --show-source --statistics
        
    - name: Test with pytest
      run: |
        python -m pytest -v

    - name: Test coverage
      run: |
        coverage run -m pytest -v
        coverage report -m --fail-under=86
