name: jarvis-ci

on:
  pull_request:
    branches:
    - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install bc
      run: |
        sudo apt-get update
        sudo apt-get install -y bc
  
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint with flake8
      continue-on-error: false
      run: |
        flake8 . --show-source --statistics
        
    - name: Test with pytest
      continue-on-error: false
      run: |
        python -m pytest -v

    - name: Test coverage
      run: |
        coverage run -m pytest -v
        coverage report -m
        coverage_percentage=$(coverage report | grep TOTAL | awk '{print $NF}')
        if [ $(echo "$coverage_percentage < 1.0" | bc -l) -eq 1 ]; then
          echo "Test coverage below 85%: $coverage_percentage%"
          exit 1
        fi
