# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alca-jarvis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jarvisai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9650722008e84cfa88080536eccb9b5d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_50f15d59aa064a7db7fa7d12c644d0fb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jarvisai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9650722008e84cfa88080536eccb9b5d }}/jarvis:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alca-jarvis'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cc1992fe5ec2418780cbe4ceb62ad59e }}
        images: 'jarvisai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9650722008e84cfa88080536eccb9b5d }}/jarvis:${{ github.sha }}'